// Code generated by entc, DO NOT EDIT.

package tweet

import (
	"time"
)

const (
	// Label holds the string label denoting the tweet type in the database.
	Label = "tweet"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"

	// EdgeCreator holds the string denoting the creator edge name in mutations.
	EdgeCreator = "creator"

	// Table holds the table name of the tweet in the database.
	Table = "tweets"
	// CreatorTable is the table the holds the creator relation/edge.
	CreatorTable = "tweets"
	// CreatorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CreatorInverseTable = "users"
	// CreatorColumn is the table column denoting the creator relation/edge.
	CreatorColumn = "user_tweets"
)

// Columns holds all SQL columns for tweet fields.
var Columns = []string{
	FieldID,
	FieldMessage,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Tweet type.
var ForeignKeys = []string{
	"user_tweets",
}

var (
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
)
