// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/francismarcus/entgql/ent"
)

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Username string `json:"username"`
}

type Todo struct {
	ID   string    `json:"id"`
	Text string    `json:"text"`
	Done bool      `json:"done"`
	User *ent.User `json:"user"`
}
