// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateProgramInput struct {
	Name    string `json:"name"`
	Creator int    `json:"creator"`
}

type CreateUserInput struct {
	Username string `json:"username"`
}
