// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/francismarcus/entgql/ent"
)

type AuthPayload struct {
	User  *ent.User `json:"User"`
	Token *string   `json:"token"`
}

type CreateProgramInput struct {
	Name    string `json:"name"`
	Creator int    `json:"creator"`
}

type CreateUserInput struct {
	Username string `json:"Username"`
}

type FollowUserInput struct {
	FollowID int `json:"FollowID"`
	UserID   int `json:"UserID"`
}

type LoginUserInput struct {
	Username string `json:"Username"`
	Password string `json:"Password"`
}

type SignupUserInput struct {
	Email    string `json:"Email"`
	Username string `json:"Username"`
	Password string `json:"Password"`
}

type UnFollowUserInput struct {
	FollowID int `json:"FollowID"`
	UserID   int `json:"UserID"`
}

type UsernameAvailableInput struct {
	Username string `json:"username"`
}
