// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Program is the predicate function for program builders.
type Program func(*sql.Selector)

// Tweet is the predicate function for tweet builders.
type Tweet func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
